# This is a basic workflow to help you get started with Actions

name: Frist-Workflow
# Controls when the workflow will run
on: workflow_dispatch
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu:latest
    steps:
      - name: print greeting
        run: echo Hello, world!
      - name: print GoodBy
        run: echo Good By!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
